### ISSUE TITLE
OS X gem install issues

### ISSUE THREAD

**Issue by farzonl** [keepcosmos/terjira#12]
https://github.com/sass/sass/issues/1768

OSX 10.11+ has a security feature that prevents modification of Rootless system files.

this works
sudo gem install -n /usr/local/bin terjira

this does not:
sudo gem install terjira

**Comment by keepcosmos** [comment]
Thanks, I added this issue on README.md
But I am not sure all OSX 10.11+ have this issue. Actually It works well on Sierra(without any ruby version management system).
