### ISSUE TITLE
proxy configuration needs exposing

### ISSUE THREAD

**Issue by digitalsushi** [keepcosmos/terjira#15]
The JIRA:Client that Terjira uses appears to have a proxy that is configurable.  It also has a flag to disable TLS chain trust checking.  For my corporate use case, I'd need to accept self signed certs and assign a proxy  with proxy credentials (user/pass).  

I'm on my personal account but I want to introduce this to the development teams being force migrated to Jira at a random fortune 50.

**Comment by keepcosmos** [comment]
@digitalsushi Thanks for reporting, I will do as soon as possible. :)

**Comment by keepcosmos** [comment]
@digitalsushi I just release v0.3.0 with proxy configuration feature. e545b778c9a18f37923d28d7864a5495d8f0aead
Could you try login with --proxy-config option `jira login --proxy-config`
