### ISSUE TITLE
Installation on OSX (Darwin 10.12.2 64bit) fails with a dependencies issue

### ISSUE THREAD

**Issue by spalter** [keepcosmos/terjira#16]
### Installation
Tested commands: 
- `sudo gem install -n /usr/local/bin terjira`
- `gem install terjira`

### Result
```
ERROR:  While executing gem ... (Gem::DependencyError)
Unable to resolve dependencies: terjira requires pastel (~> 0.6.1); tty-table requires pastel (~> 0.6.0)
```

### Environment
```
gem --version
2.0.14.1
Darwin 10.12.2 64bit
```

**Comment by keepcosmos** [comment]
@spalter Thanks for reporting, I resolved the issue and just release new version. Please check :)
