### ISSUE TITLE
`jira issue ls` returns errors

### ISSUE THREAD

**Issue by 5minpause** [keepcosmos/terjira#17]
The command works, I guess, but the errors seem to have to do with our Jira configuration. The result is, I cannot list issues:

```
~ % jira issue ls

Der Wert 'Aufgaben' existiert nicht für das Feld 'statusCategory'.
Der Wert 'In Arbeit' existiert nicht für das Feld 'statusCategory'.
Der Wert 'Keine Kategorie' existiert nicht für das Feld 'statusCategory'.
```

The errors are in German. I could translate them if you need me to.

**Comment by keepcosmos** [comment]
Thanks. Your reporting was really helpful for improving terjira.
It was a I18n problem. It was fixed. Please update to 0.3.1 👍
