### ISSUE TITLE
The backlog is not available on Kanban boards

### ISSUE THREAD

**Issue by nicolaskruchten** [keepcosmos/terjira#19]
Thanks for this tool, it's really neat!

I'm trying to list the backlog for my Kanban boards and getting `The backlog is not available on Kanban boards` but in fact this feature was recently added to JIRA... would it be possible for terjira to support it as well?

**Comment by keepcosmos** [comment]
Thanks :)

Are there any differences between "Kanban backlog" and "Issues of a project"? 
Is `jira issue ls -p PROJECT`(with other options) not enough?

**Comment by nicolaskruchten** [comment]
Yes, the difference is that a board (Kanban or Scrum, they work the same way) operates on a stored query which is often more complex than just "project=X". So I could in theory use the JQL command to list my issues but I would have to remember the complex query for each board...

**Comment by keepcosmos** [comment]
Ok, I understand. but I can not find api than support kanban features (https://docs.atlassian.com/jira-software/REST/cloud/#agile/1.0/board)

So, Do you mean you want control kanban board with "Swimlanes" and "Quick filter"
Could you give me some example?
