### ISSUE TITLE
Error when creating Issue

### ISSUE THREAD

**Issue by donkey-hotei** [keepcosmos/terjira#2]
Hello keepcosmos, I love the potential of this tool! Would absolutely love to work with JIRA via the command line. However, currently there is issue when creating a new issue !

```Choose isseu type? Task
Summary? AAAAA
summary: Operation value must be a string 
```

Is there is possible fix or reason? Thanks. Also, one should note that if one enters in an email for the username (and successfully authenticates) this error occurs when attempting to list issues

```Error in the JQL Query: The character '@' is a reserved JQL character. You must enclose it in a string or use the escape '\u0040' instead. (line 1, character 17) ```

**Comment by keepcosmos** [comment]
Thanks @donkey-hotei 

I will 

And `Operation value must be a string` is from JIRA Rest API response. Could you tell me What text did you write on issue summary?
