### ISSUE TITLE
`jira issue new` throwing an error

### ISSUE THREAD

**Issue by iJebus** [keepcosmos/terjira#20]
Running tejira 0.3.2. Finding it less than immediately obvious to discover what version of Jira Rest API and Agile Rest API is running so apologies in advance if this is likely to be the problem.

```bash
jira issue new

Choose project? (Use arrow keys, press Enter to select)
‣ ADM - Admin
  DEV - Development

Choose project? ADM - Admin
default index `1` out of range (1 - 0)
```

The same error is thrown for either selection. List commands are working however and some of the other stuff (e.g. commenting).

**Comment by keepcosmos** [comment]
Could you tell me which version of `tty-prompt` are you using?

**Comment by iJebus** [comment]
Sure, that's tty-prompt (0.9.0) on ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16].

**Comment by keepcosmos** [comment]
@piotrmurach Chould you give me some hint?

**Comment by piotrmurach** [comment]
Hi,

The error `default index `1` out of range (1 - 0)` is only thrown when index of default option is out of range of all choices. The zero means that the array of projects is empty at this point. By default `tty-prompt` will set first element in the array as default choice. However, if the menu is created with no choices then it will throw an error. I would suspect that at this point there are no projects fetched. To replicate this error do:
```ruby
prompt = TTY::Prompt.new('Choose project?', [ ], 1)
```
When I wrote that code I wanted to make sure that prompt cannot be created without the actual menu items. I suppose I could add another error that specifically tells you that you are trying to create an empty menu. Would that help?

**Comment by keepcosmos** [comment]
Thanks, @piotrmurach 

@iJebus said,

> Choose project? (Use arrow keys, press Enter to select)
> ‣ ADM - Admin
>    DEV - Development

and
> Choose project? ADM - Admin

are printed.

I also checked, https://github.com/piotrmurach/tty-prompt/blob/82750f4c56b5e8decd8d822b79fce29af17d1c8e/lib/tty/prompt/list.rb#L177-L188

@iJebus can you debug?
