### ISSUE TITLE
Nothing happens on `issue edit [ISSUE_KEY]`

### ISSUE THREAD

**Issue by williamn** [keepcosmos/terjira#24]
Hi there,

Good works on `terjira`. Really helpful app.

I have a problem right now. Nothing is happening after I execute `issue edit [ISSUE_KEY]`.

What could be possibly wrong?

I have set my `$EDITOR`.

**Comment by keepcosmos** [comment]
Terjira does not work with your editor, it builds interactive prompt menu.
You can pass options for updating the issue.

for example)

    jira issue edit TEST-1 --summary --description --assignee

Please check `jira issue help edit`

And I also worked for avoiding confusion from just return empty(7d401441c4dfea5ee62fd1403ec5dfce9aa7652c)

Thanks for reporting :)

**Comment by williamn** [comment]
What editors are working right now?

I'm using vim.

**Comment by keepcosmos** [comment]
@williamn Sorry, I mean Terjira does not open any editor. Terjira offers own interactive prompt.

**Comment by williamn** [comment]
Ah Ok. Thanks!
