### ISSUE TITLE
jira issue comment drops characters - i.e. $

### ISSUE THREAD

**Issue by neil-bowers** [keepcosmos/terjira#25]
Attempts to create a comment on an issue with the following syntax result in all characters immediately following the `$` being dropped.

`jira issue comment <ISSUE#> -m "OPS$HRT blah blah blah"`

The `$HRT` is dropped from the comment, presumably because `$` is being interpreted as a special character, but it should be ignored since it's contained within a string.

**Comment by keepcosmos** [comment]
It is a shell issue. Actually the way how to handle `$` sign in shell.

You can use option like `-m 'OPS$HRT blah blah` or `-m "OPS\$HRT blah blah`
