### ISSUE TITLE
jira issue [ISSUE_KEY] fails

### ISSUE THREAD

**Issue by chrisbward** [keepcosmos/terjira#26]
Hi,

Trying to run this command, I get;

jira issue XXX-XXX                                                                                                                                                         16:52:04 
/home/developer/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse': 784: unexpected token at '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Oops, you&#39;ve found a dead link. - JIRA</title><script type="text/javascript">contextPath = "";</script><link type='text/css' rel='stylesheet' href='/static-assets/metal-all.css' media='all'>

**Comment by keepcosmos** [comment]
It looks like Jira issue. All your jira issues raise that errors or specific issue?

**Comment by chrisbward** [comment]
could this be related to the leading slash? would be good to have a debug option to see which urls are being requested - I'm not familiar enough with ruby and the build process to help, sorry mate

**Comment by keepcosmos** [comment]
Maybe related to #30

**Comment by chrisbward** [comment]
I'm no longer working with JIRA - but will let you know next time I get to test!

**Comment by keepcosmos** [comment]
@chrisbward Thanks!
