### ISSUE TITLE
issue open [ISSUE_KEY] not opening browser on Ubuntu 16.04

### ISSUE THREAD

**Issue by chrisbward** [keepcosmos/terjira#27]
Running $jira issue open XXX-XXX on Ubuntu 16.04, I get; 
                                                                                                                                         
 16:54:13 
Platform $OSTYPE not supported
No such file or directory - https://jira.-----.com//browse/XXX-XXX

Observe the double /

**Comment by keepcosmos** [comment]
Thanks, It's just fixed and released. Try after update :)

**Comment by chrisbward** [comment]
Now opens the browser, but the URL has a leading slash (/)
