### ISSUE TITLE
jira issue new - default index `1` out of range (1 - 0)

### ISSUE THREAD

**Issue by chrisbward** [keepcosmos/terjira#28]
typing in;

$jira issue new

I'm presented with a list of choices - these are populated fine
I choose the second item, app bails with;

default index `1` out of range (1 - 0)

**Comment by keepcosmos** [comment]
I can not figure it out. I think it is a [tty-prompt](https://github.com/piotrmurach/tty-prompt) issue. Can you give me more detail? or Can you debug it?
