### ISSUE TITLE
SSL_connect error

### ISSUE THREAD

**Issue by jampow** [keepcosmos/terjira#3]
I got the following error at login:
`SSL_connect returned=1 errno=0 state=error: certificate verify failed`

**Comment by skyksandr** [comment]
Solved this problem by explicitly providing path to certificate:
`SSL_CERT_FILE=~/Documents/MyCompanyCA.pem jira login`

**Comment by jampow** [comment]
it didn't work @skyksandr. 

I downloaded the certificate like described [here](http://superuser.com/questions/97201/how-to-save-a-remote-server-ssl-certificate-locally-as-a-file) but the error persists :-/

**Comment by keepcosmos** [comment]
What is your environment? Are you using rvm and osx?

**Comment by piotrmurach** [comment]
@jampow I don't think this is anything to do with this library but the rubygems and in particular gem installation on your system. I would hazard a guess that you're using a system without root certs such as Windows? In any way, this is easily fixed by following the [rubygems guides](http://guides.rubygems.org/ssl-certificate-update/).

**Comment by 5minpause** [comment]
> rubygems and in particular gem installation on your system

I am on macOS sierra and running rubygems and rails and friends without problems.
Do you have any other idea what might cause this problem?

Our jira instance doesn't run on https (yet).

**Comment by keepcosmos** [comment]
@5minpause When does it cause error? When installing gem or login in terjira?

**Comment by 5minpause** [comment]
When logging into jira @keepcosmos 

```
~ % jira login
Login will be required...
Site: http://[redacted]
Context path:
Username: [redacted]
Password: •••••••••••
SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
```

**Comment by piotrmurach** [comment]
I believe this is a different issue, the error is very different from the original `certificate verify failed`. This seems like a connection configuration problem. I don't know how this library connects with JIRA api but I would be inclined to say that the there should be an option to specify SSL version and how or whether the certs should be verified. In your case probably disabling SSL would do the trick. I think I would first try to use `openssl` or write ruby script that makes direct call from your machine to jira instance.

**Comment by keepcosmos** [comment]
@5minpause I am fixing, Currently terjira support only ssl.

**Comment by keepcosmos** [comment]
@5minpause Could you update to v0.3.0 and try?
You can login with `--ssl-config` option. But simply you pass http protocol url without the option when terjira ask 'Site', It will work.

**Comment by 5minpause** [comment]
Thank you @keepcosmos 
v0.3.0 works for me with connecting. I had other issues now. I opened new tickets. 😄

**Comment by jampow** [comment]
Sorry about de delay. It worked to me too! tks @keepcosmos
