### ISSUE TITLE
vim keybindings

### ISSUE THREAD

**Issue by kyranjamie** [keepcosmos/terjira#31]
Would be nice to navigate lists with `j` and `k`

It's quite standard for cli projects like this, so would be an asset to the project.

**Comment by keepcosmos** [comment]
Thanks for suggesting. Terjira is based on [tty-prompt](https://github.com/piotrmurach/tty-prompt).  Changing key binding terjira itself is very hard work. Please make request to tty-prompt :)

**Comment by kyranjamie** [comment]
Has already been suggested, in response they implemented: https://github.com/piotrmurach/tty-prompt#212-keyboard-events

**Comment by keepcosmos** [comment]
Oh, thanks for the info, I will open the issue and try to figure it out

**Comment by keepcosmos** [comment]
Added j, k, Ctrl+n, Ctrl+p
Thanks for reporting. Please check new version!

**Comment by kyranjamie** [comment]
Great work 💯
