### ISSUE TITLE
Credentials file permission

### ISSUE THREAD

**Issue by michaelmior** [keepcosmos/terjira#32]
I see that under `~/.terjira`, the file which contains the login credentials has group read permissions. I'd suggest that this should only be readable by the current user since no one else should have access to the password.

**Comment by keepcosmos** [comment]
It's very reasonable feature. Thanks for suggestion.

**Comment by keepcosmos** [comment]
@michaelmior Thanks I just released 0.3.4

**Comment by michaelmior** [comment]
Thanks!
