### ISSUE TITLE
Proxy configuration result in end of file reached

### ISSUE THREAD

**Issue by drscream** [keepcosmos/terjira#35]
I tried to configure `terjira` with an proxy option, which is a local SSH tunnel SOCKS proxy. But at the end of the configuration I receive the message `end of file reached`. The configuration isn't saved.

### Full output:

```
 » jira login --proxy-config
Login will be required...
Site: https://random.example.com
Context path: 
Username: my-user@example.com
Password: ••••••••••••
Proxy address:  127.0.0.1
Proxy port:  7070
end of file reached
```

**Comment by drscream** [comment]
Do you may need more information?

**Comment by keepcosmos** [comment]
Yes, please give more information :)
I am struggling with ruby ssl configuration and have not found what problem is.

**Comment by drscream** [comment]
I somehow assume the error happen here `JIRA::Client.new(build_auth_options)` so it try to login but the proxy part somehow break the JIRA::Client login connection so it's never successful.

**Comment by keepcosmos** [comment]
This error is kind of IOError. Could you try to access to your api endpoint with `curl`?

**Comment by drscream** [comment]
The command below works well! I also used the `--socks5` parameter and added the `project.example.com` to `/etc/hosts`. But maybe it's not a socks proxy which is configured with your parameter?

```
curl -D- --socks5-hostname 127.0.0.1:7070 https://project.example.com/
```

**Comment by keepcosmos** [comment]
You're right. Actually it's hard to find out what problem is. Terjira is ruby-jira gem.
here is authentication code. 
https://github.com/sumoheavy/jira-ruby/blob/v1.1.1/lib/jira/client.rb#L5

Can you debug?

**Comment by drscream** [comment]
Thanks for the information. It's really an HTTP proxy not an SOCKS proxy, so I assume it will never work with my SOCKS proxy :-) I think the first idea would be to replace:

```
[--proxy-config] with proxy configuration
```

with:

```
[--proxy-config] with http proxy configuration
```

So it's clear for everybody it's not a SOCKS5 proxy configuration option. There are solutions like `socksify` which provides `Net::HTTP.SOCKSProxy` for the connection, but I assume this is out of scope. I would say this is no longer a bug :-)

I may provide a feature request for https://github.com/sumoheavy/jira-ruby to support SOCKS proxies as well.

**Comment by keepcosmos** [comment]
Thanks :) Just let me know if you need help!
