### ISSUE TITLE
login

### ISSUE THREAD

**Issue by MadBomber** [keepcosmos/terjira#36]
It bothers me that I have to reset my creds.  Once I do a login to establish my creds to the jira server I don't want to do it again - because I can never remember what terjira wants for the site and context options.  Does site include the protocol or not?  Does site only need the domain.  What does context path mean?  If would be very helpful to forgetful old men to have some example in the documentation or help output.

**Comment by keepcosmos** [comment]
Thanks for reporting, I just released new version that contains your suggestion. 👍
