### ISSUE TITLE
Feature request: jira issue comment <ticket> should open vim

### ISSUE THREAD

**Issue by aronneagu** [keepcosmos/terjira#40]
Hi,

I would like to request that when commenting an issue, to have vim open up, add the comments there, and after closing vim to send the contents as comment for the issue.
My main trouble with doing "jira issue comment <ticket>" is that after entering a line, I cannot go back and edit it. 

Do you think this would be possible? Thanks

**Comment by keepcosmos** [comment]
Thanks for reporting. And I also understand what you need. I will consider your request at next milestone although it's hard to add the feature now.

**Comment by aronneagu** [comment]
Its not an urgent request, more of "nice feature to have at some point". Thank you for considering it.

**Comment by keepcosmos** [comment]
@kimpers add the feature, please download new version and check!
