### ISSUE TITLE
Feature request: get Jira URL for issue

### ISSUE THREAD

**Issue by aronneagu** [keepcosmos/terjira#41]
Hi.
I would like to request a new command that would return me the URL for an issue, something like
jira issue url <issue>   --> https://<company>.atlassian.net/browse/<issue>

When doing git commits, we add the URL of the Jira issue as the git comment, and currently just to get the URL I need to visit Jira in a webbrowser. This is the only scenario when I have to access Jira in a browser, otherwise terjira is quite complete and allows me to do everything else from the CLI. Thanks

**Comment by keepcosmos** [comment]
Thanks for suggesting feature!, I will consider the feature! 😄

**Comment by keepcosmos** [comment]
@kimpers added the feature. and it is just released! 

Thanks!
