### ISSUE TITLE
Sprint command doesn't list issues

### ISSUE THREAD

**Issue by tylerjpines** [keepcosmos/terjira#44]
Loving terjira so far! I'm trying to set up an easy way to pull my team's current backlog (easily done with (`jira board backlog -b BOARD_ID`), and active sprint items. It doesn't seem possible to get issues under a current sprint:
```
$ jira sprint active -b 1382 -a ALL
3278. Grand-Fermage  Active
Tue Sep 12 13:40:43 2017 ~ Fri Sep 29 20:47:00 2017
```

I've tried every possible combination, but no issues show up. Seems like a bug?

Thanks for doing this amazing project!

**Comment by keepcosmos** [comment]
Thanks for reporting! 
I just release fixed version. Please update with `gem update terjira`. Enjoy! 👍
