### ISSUE TITLE
Transition issue through multiple steps

### ISSUE THREAD

**Issue by KillaPL** [keepcosmos/terjira#48]
Hello

Would it be possible to transition issue through multiple steps when doing `jira issue trans` ?
I'm asking if it's doable from the API point of view, and if you would have that in the project.

If the answer is yes, I could give it a try, I'm spending quite some time in my work moving jira tasks around.

EDIT

I will often cleanup some boards and put multiple issues to final stage to "DONE". So I would like to add batch transitions through multiple steps to the question : ). Maybe this could be new feature? I would still be happy to implement it.

**Comment by keepcosmos** [comment]
Thanks :) It will be a good feature, please write code 👍

**Comment by KillaPL** [comment]
I was looking through the code and thinking about how this can be done, but the codebase is quite complex... I don't think I will be able to easily extend the codebase with the time I have. Sorry: (

Your project is still amazing! Just quite difficult to understand in the code...
