### ISSUE TITLE
Does not list all boards

### ISSUE THREAD

**Issue by ktalebian** [keepcosmos/terjira#52]
Our organization has a large list of boards. However, `jira board ls` does not show all of them. Is there a way I can set my active board via a command?

**Comment by keepcosmos** [comment]
No, How about `less`

**Comment by ktalebian** [comment]
@keepcosmos sorry not sure what you mean by `less`?

**Comment by keepcosmos** [comment]
Sorry, I mean 
http://www.tutorialspoint.com/unix_commands/less.htm

**Comment by ktalebian** [comment]
That wouldn't help though. `jira board ls` is not returning all my available boards. I don't see how piping an incomplete list into `less` will help with that.

**Comment by piotrmurach** [comment]
I'm not sure how this feature is implemented but you could use newest [tty-prompt select/multi_select](https://github.com/piotrmurach/tty-prompt#262-select) to handle this. It paginates lists by default, you can specify the number of items per page etc... It is really powerful!

Alternatively, you can use [tty-pager](https://github.com/piotrmurach/tty-pager) to page any long output either through native unix utility or pure Ruby output paging.
