### ISSUE TITLE
Deprecated Gem warning is very annoying (what can be done?)

### ISSUE THREAD

**Issue by jschank** [keepcosmos/terjira#63]
Everytime I run any terjira command I get this:

> NOTE: Gem.gunzip is deprecated; use Gem::Util.gunzip instead. It will be removed on or after 2018-12-01.
Gem.gunzip called from /Users/jschank/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/unicode-display_width-1.1.3/lib/unicode/display_width/index.rb:5.

Is there some way to update the dependency in a way that fixes what it is asking for? Or can the warning be suppressed, if I cannot repair the situation?

**Comment by jschank** [comment]
Also, I'd like to say I love this project, and I use it everyday.
Much appreciated.

**Comment by keepcosmos** [comment]
I just release new version `0.4.2`, 
These days I don't use jira for work, so I couldn't fegure it out. 

Update terjira and please check.

**Comment by jschank** [comment]
I noticed I pulled and updated gem today 0.4.2
And it fixes this problem.

I really appreciate the fix!
Thank you.

**Comment by jschank** [comment]
@keepcosmos I noticed something else.
Often the box around the ticket, when terjira renders information in terminal, would have a vertical bar that was a few characters to the right, and out of alignment.
I ignored it because I thought it was a result of the font I'm using.

It seems this update has the happy side-effect of fixing that problem too.

Two bugs, one bullet. Nice work!

**Comment by keepcosmos** [comment]
I just update tty-table gem. thanks @piotrmurach :)
