### ISSUE TITLE
jira issue [ISSUE_KEY] returns nothing

### ISSUE THREAD

**Issue by skyksandr** [keepcosmos/terjira#7]
I'm able to list issues, but unable to view issue details. Is there any way to do some diagnostics?

**Comment by keepcosmos** [comment]
Could you try `issue comment ISSUE_KEY` or `issue trans ISSUE_KEY`? Does it work?
or
Could you try from source code? Under project path `bin/jira issue [ISSUE-KEY]` and debug. Could you?

**Comment by skyksandr** [comment]
@keepcosmos Sorry for late reply. I'll debug it in few days and report back.

**Comment by keepcosmos** [comment]
@skyksandr Thank you!! :)

**Comment by keepcosmos** [comment]
@skyksandr please reopen when anything is updated.
