### ISSUE TITLE
documentation update to indicate password is api token for some login workflows

### ISSUE THREAD

**Issue by unphased** [keepcosmos/terjira#74]
I usually use my company google account to log into jira (it's in another company's system). 

I found through trial and error that when I login with terjira it works when I use my email and set the password to an app token that I set up in the atlassian security settings. 

There is nothing that hints at this in any of this repo's documentation (or issues) so I wanted to leave a note here so that others can find the info to set this system up.

**Comment by Menda** [comment]
Just in case anyone wonders, go to "Manage your account" in https://id.atlassian.com/manage-profile/general

Then go to the section "Security" and under "API Token", click on "Create and manage API tokens". Then generate set a label "terjira" and copy the token generated, which will be used as the password asked in terjira.
