### ISSUE TITLE
Migrate to latest stable versions of active support and thor

### ISSUE THREAD

**Issue by asm0dey** [keepcosmos/terjira#88]
Hi!

I'm maintainer of terjira package in Arch linux: https://aur.archlinux.org/packages/terjira/

Today, after update of ruby-activesupport and ruby-thor to latest versions terjira stooped working. As workaround I've created packages with old versions of ruby-tzinfo, ruby-activesupport and ruby-thor, but it looks pretty ugly. Please, add support for new versions of libraries.

**Comment by ghosteathuman** [comment]
HI @asm0dey, Active Support has been bumped to `6.0.3.1` #92 and thor has been bumped to `1.0.1` #93 

0.4.6 Release #94 will be soon. Hope this issue is resolve then.

**Comment by ghosteathuman** [comment]
Hi @asm0dey 0.4.6 has been released. Can we go ahead and close this issue?

**Comment by asm0dey** [comment]
Yes, thank you!

**Comment by snpefk** [comment]
Well, it happened again.
On Manjaro terjira stop working because `activesupport` update to "6.0.3."` version. Can you please update dependencies?

**Comment by ghosteathuman** [comment]
A [recently merged PR](https://github.com/keepcosmos/terjira/pull/101) loosens the dependencies requirement.

Hopefully when this is released the issue will be resolved.
