### ISSUE TITLE
Login using Google Account?

### ISSUE THREAD

**Issue by andyw8** [keepcosmos/terjira#9]
My organisation's site is hosted at https://something.atlassian.net.

Authentication is by Google rather than Atlassian Cloud.

Do you have any plans to support this?

**Comment by keepcosmos** [comment]
I have no idea about using oauth2 in console with jira account. But after resetting your password, you can use basic authentication and oauth for JIRA even though you are using google acount.

**Comment by andyw8** [comment]
It's not possible to reset it – it only allows authentication by Google, so it doesn't recognise my email address.

**Comment by keepcosmos** [comment]
@andyw8 I am using atlassian cloud with google authentication like. Change password reset or receive forget password mail to the gmail account that is authenticated

**Comment by andyw8** [comment]
As as I said, it doesn't work for me. Trying to reset it fails with:

> Sorry, we didn't recognize that username and password combination. Please double-check and try again.

Perhaps the account administrator has control over whether non-Google sign-ins are allowed.

**Comment by keepcosmos** [comment]
@andyw8 Could you check https://answers.atlassian.com/questions/76747/does-basic-http-authentication-work-for-google-apps-bound-jira-on-demand-instances

**Comment by andyw8** [comment]
Thanks for the link, but I think that information may be out of date. (OnDemand was rebranded to Atlassian Cloud).

> When you first signed in to your OnDemand instance via Google Apps, you would have been prompted to create an 'OnDemand password'

I don't believe I was ever prompted for that.

> If you don't recall this password, you can have your administrator set your password to something known

I'll try asking my administrator about that after the holidays.

**Comment by keepcosmos** [comment]
@andyw8 Thanks for trying :)
