### ISSUE TITLE
undefined method `name' for #<JIRA::Resource::User:0x00007fdbab0bb128>

### ISSUE THREAD

**Issue by nathan-fiscaletti** [keepcosmos/terjira#91]
This is to draw attention to #89 which was closed but is not resolved for most users.

**Comment by ghosteathuman** [comment]
Hi @nathan-fiscaletti, I am looking at #89 and it seems the issue about `undefined method 'name' for #<JIRA::Resource::User:0x00007fdbab0bb128>` was resolved with #90 

That fix isn't release yet (working on it with @keepcosmos ). In the meantime, have you tried pulling the main branch & building + installing locally to see if it resolves the issue you are facing?

I will note that there is another issue `gem/ruby/2.7.0/gems/terjira-0.4.5/lib/terjira/client/issue.rb:10: warning: deprecated Object#=~ is called on JIRA::Resource::User; it always returns nil Empty` that is not being addressed yet.

**Comment by ghosteathuman** [comment]
Hi @nathan-fiscaletti 0.4.6 has been released. Appreciate it if you can test and see if that issue is still happening for you.

**Comment by ghosteathuman** [comment]
I will be closing this issue end of the month (September). 

@nathan-fiscaletti If you are still having issues, feel free to comment here. If not, raise another issue then.
